 const data=[
   {
    name:'名称',
    risk:'涨幅',
    number:'代码',
    else:'其他',
    abc:'abc',
    edit:'备注'
   },
  {
    name:'国金证券',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券1',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券2',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券3',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券4',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券1',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券2',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券3',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券4',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券1',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券2',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券3',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券4',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券1',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券2',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券3',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
  {
    name:'国金证券4',
    risk:'70%',
    number:'600109',
    else:'nothing',
    abc:'abc',
    edit:'hhhh'
  },
];
export default data;